7 octobre 2019 13:37:08	Error during importation process: CutQueue.Lib.JobImporter.InvalidPartHeightException: Invalid part height " 758.83".
   à CutQueue.Lib.JobImporter.JobImporter.ImportJobFromCSVFile(FileInfo fileInfo) dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 168
   à CutQueue.Lib.JobImporter.JobImporter.<ImportJobFromCSVFileAndExportToFabplan>d__0.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 24
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.ImportCSV.<ImportAllCSV>d__3.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\ImportCSV.cs:ligne 81
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.ImportCSV.<DoSync>d__2.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\ImportCSV.cs:ligne 40

7 octobre 2019 14:11:48	Error during importation process: CutQueue.Lib.JobImporter.InvalidPartHeightException: Invalid part height " 758.83".
   à CutQueue.Lib.JobImporter.JobImporter.ImportJobFromCSVFile(FileInfo fileInfo) dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 171
   à CutQueue.Lib.JobImporter.JobImporter.<ImportJobFromCSVFileAndExportToFabplan>d__0.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 24
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.ImportCSV.<ImportAllCSV>d__3.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\ImportCSV.cs:ligne 81
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.ImportCSV.<DoSync>d__2.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\ImportCSV.cs:ligne 40

8 octobre 2019 15:31:40	Error during importation process: CutQueue.Lib.JobImporter.InvalidPartGrainDirectionException: Invalid part grain direction "0".
   à CutQueue.Lib.JobImporter.JobImporter.ExtractPartFromCsvEntry(CsvReader& csvReader) dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 250
   à CutQueue.Lib.JobImporter.JobImporter.ImportJobFromCSVFile(FileInfo fileInfo) dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 96
   à CutQueue.Lib.JobImporter.JobImporter.<ImportJobFromCSVFileAndExportToFabplan>d__2.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 32
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.ImportCSV.<ImportAllCSV>d__3.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\ImportCSV.cs:ligne 84
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.ImportCSV.<DoSync>d__2.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\ImportCSV.cs:ligne 38

8 octobre 2019 15:33:25	Error during importation process: CutQueue.Lib.JobImporter.InvalidPartGrainDirectionException: Invalid part grain direction "0".
   à CutQueue.Lib.JobImporter.JobImporter.ExtractPartFromCsvEntry(CsvReader& csvReader) dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 250
   à CutQueue.Lib.JobImporter.JobImporter.ImportJobFromCSVFile(FileInfo fileInfo) dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 96
   à CutQueue.Lib.JobImporter.JobImporter.<ImportJobFromCSVFileAndExportToFabplan>d__2.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 32
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.ImportCSV.<ImportAllCSV>d__3.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\ImportCSV.cs:ligne 84
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.ImportCSV.<DoSync>d__2.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\ImportCSV.cs:ligne 38

8 octobre 2019 15:39:25	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.FabplanHttpResponseFailureException: The provided job has no specified name.
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 201
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 15:39:44	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.FabplanHttpResponseFailureException: The provided job has no specified name.
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 201
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 15:39:56	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.FabplanHttpResponseFailureException: The provided job has no specified name.
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 201
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 15:40:56	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.FabplanHttpResponseFailureException: The provided job has no specified name.
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 201
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 15:45:37	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 15:55:20	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 15:56:39	Error during importation process: System.Exception: Failed to determine if job "71999P" exists. ---> System.FormatException: La chaîne n'a pas été reconnue en tant que Boolean valide.
   à System.Boolean.Parse(String value)
   à System.String.System.IConvertible.ToBoolean(IFormatProvider provider)
   à System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   à Newtonsoft.Json.Utilities.ConvertUtils.TryConvertInternal(Object initialValue, CultureInfo culture, Type targetType, Object& value)
   à Newtonsoft.Json.Utilities.ConvertUtils.Convert(Object initialValue, CultureInfo culture, Type targetType)
   à Newtonsoft.Json.Linq.JValue.JValueDynamicProxy.TryConvert(JValue instance, ConvertBinder binder, Object& result)
   à CallSite.Target(Closure , CallSite , Object )
   à CutQueue.Lib.JobImporter.JobImporter.<JobExists>d__13.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 418
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<JobExists>d__13.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 422
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 315
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ImportJobFromCSVFileAndExportToFabplan>d__2.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 37
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.ImportCSV.<ImportAllCSV>d__3.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\ImportCSV.cs:ligne 84
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.ImportCSV.<DoSync>d__2.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\ImportCSV.cs:ligne 38

8 octobre 2019 15:56:49	Error during importation process: System.IO.IOException: Le nom réseau spécifié n’est plus disponible.

   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileSystemEnumerableIterator`1.CommonInit()
   à System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   à System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   à System.IO.DirectoryInfo.GetFiles()
   à CutQueue.ImportCSV.<ImportAllCSV>d__3.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\ImportCSV.cs:ligne 73
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.ImportCSV.<DoSync>d__2.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\ImportCSV.cs:ligne 38

8 octobre 2019 15:59:46	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:00:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:01:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:02:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:03:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:04:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:05:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:06:46	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:07:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:08:46	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:09:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:10:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:11:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:12:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:13:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:14:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:15:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:16:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:17:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:18:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:19:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:20:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:21:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:22:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:23:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:24:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:25:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:26:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:27:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:28:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:29:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:30:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:31:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:32:20	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:32:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:33:20	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:33:53	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:35:44	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:36:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:42:51	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:43:53	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

8 octobre 2019 16:44:38	Error during importation process: System.IO.IOException: Le nom réseau spécifié n’est plus disponible.

   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileSystemEnumerableIterator`1.CommonInit()
   à System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   à System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   à System.IO.DirectoryInfo.GetFiles()
   à CutQueue.ImportCSV.<ImportAllCSV>d__3.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\ImportCSV.cs:ligne 73
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.ImportCSV.<DoSync>d__2.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\ImportCSV.cs:ligne 38

8 octobre 2019 16:45:40	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

9 octobre 2019 09:53:39	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.FabplanHttpResponseFailureException: The "JobTypeList" member of Job "71999P" is not an array.
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 201
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

9 octobre 2019 09:54:09	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.FabplanHttpResponseFailureException: The "JobTypeList" member of Job "71999P" is not an array.
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 201
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

9 octobre 2019 09:54:18	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.FabplanHttpResponseFailureException: The "JobTypeList" member of Job "71999P" is not an array.
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 201
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

9 octobre 2019 09:55:07	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.FabplanHttpResponseFailureException: The "JobTypeList" member of Job "71999P" is not an array.
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 201
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

9 octobre 2019 11:23:37	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> System.Exception: The request to the API failed. ---> Newtonsoft.Json.JsonWriterException: Unsupported type: System.Collections.Generic.SortedList`2+ValueList[System.Int32,CutQueue.Lib.Import.Model.JobType]. Use the JsonSerializer class to get the object's JSON representation. Path ''.
   à Newtonsoft.Json.JsonWriter.WriteValue(JsonWriter writer, PrimitiveTypeCode typeCode, Object value)
   à Newtonsoft.Json.JsonWriter.WriteValue(Object value)
   à Newtonsoft.Json.JsonTextWriter.WriteValue(Object value)
   à CutQueue.Lib.Import.Model.JobTypeListJsonConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer) dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\Job.cs:ligne 68
   à Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   à Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   à Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   à Newtonsoft.Json.JsonConvert.SerializeObject(Object value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 78
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 84
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

9 octobre 2019 11:40:45	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

9 octobre 2019 11:41:12	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

9 octobre 2019 11:41:32	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

9 octobre 2019 11:48:52	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

9 octobre 2019 11:49:32	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

9 octobre 2019 11:50:48	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

9 octobre 2019 11:51:43	Failed to create job "71999P": CutQueue.Lib.JobImporter.CannotCreateJobException: Job "71999P" could not be created. ---> CutQueue.Lib.Fabplan.UnexpectedFabplanHttpResponseFormatException: Response is not an object. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.JsonTextReader.Read()
   à Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   à Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   à Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   à Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 112
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<DecodeResponse>d__7.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 116
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.Fabplan.FabplanHttpRequest.<Post>d__6.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Fabplan\FabplanHttpRequest.cs:ligne 87
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 360
   --- Fin de la trace de la pile d'exception interne ---
   à CutQueue.Lib.JobImporter.JobImporter.<CreateJob>d__11.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 368
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à CutQueue.Lib.JobImporter.JobImporter.<ExportJobToFabplan>d__10.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\Model\JobImporter.cs:ligne 334.

9 octobre 2019 12:09:37	Error during importation process: System.IO.IOException: Le nom réseau spécifié n’est plus disponible.

   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileSystemEnumerableIterator`1.CommonInit()
   à System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   à System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   à System.IO.DirectoryInfo.GetFiles()
   à CutQueue.ImportCSV.<ImportAllCSV>d__3.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\ImportCSV.cs:ligne 73
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.ImportCSV.<DoSync>d__2.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\ImportCSV.cs:ligne 38

9 octobre 2019 13:58:50	Error during importation process: System.IO.IOException: Le nom réseau spécifié n’est plus disponible.

   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileSystemEnumerableIterator`1.CommonInit()
   à System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   à System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   à System.IO.DirectoryInfo.GetFiles()
   à CutQueue.ImportCSV.<ImportAllCSV>d__3.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\ImportCSV.cs:ligne 73
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   à CutQueue.ImportCSV.<DoSync>d__2.MoveNext() dans C:\Users\m.maurice\Documents\github\CutQueue\CutQueue\Lib\Import\ImportCSV.cs:ligne 38

